### ISSUE TITLE
public-address not provided

### ISSUE THREAD

**Issue by paulgear** [juju-solutions/interface-juju-info#1]
@chuckbutler Any reason this interface doesn't include public-address?  This seems to me the most useful thing that the juju-info provides.

**Comment by paulgear** [comment]
Also, is {requires:etcd} in requires.py a typo?  I would have thought that should be {requires:juju-info}.

**Comment by paulgear** [comment]
@marcoceppi Confirmed for me in IRC that juju-info doesn't provide public-address, and that I'll have to get that from unit_get.

**Comment by lazypower** [comment]
Well, you had a great comment about etcd being in there, which it shouldn't be! #2 resolves this
